"""Create purchases table

Revision ID: 6b85cd9f194a
Revises: f7438d9d1642
Create Date: 2024-02-25 19:44:18.326202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6b85cd9f194a'
down_revision: Union[str, None] = 'f7438d9d1642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "purchases",
        sa.Column("purchase_id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("software", sa.String()),
        sa.Column("status", sa.String(), server_default="Unpaid"),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"]),
        sa.PrimaryKeyConstraint("purchase_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("purchases")
    # ### end Alembic commands ###
