"""Create completed_purchases table

Revision ID: 7612b8c21a20
Revises: 6b85cd9f194a
Create Date: 2024-03-10 07:49:39.183778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7612b8c21a20"
down_revision: Union[str, None] = "6b85cd9f194a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "completed_purchases",
        sa.Column("purchase_id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("software", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="Paid", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"]),
        sa.PrimaryKeyConstraint("purchase_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("completed_purchases")
    # ### end Alembic commands ###
